name: Deploy SaviyntWrapper to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SAVIYNT_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SAVIYNT_AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="saviynt_aws_access_key=${{ secrets.SAVIYNT_AWS_ACCESS_KEY }}" -var="saviynt_aws_secret_key=${{ secrets.SAVIYNT_AWS_SECRET_KEY }}"
        working-directory: infrastructure

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push SaviyntWrapper image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: saviynt-wrapper
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster saviynt-cluster --service saviynt-service --force-new-deployment